-- NEED TO RUN MANUALLY, AS THE \connect COMMAND IS NOT COMPATIBLE WITH FLYWHEEL (ONLY EXECUTES PURE SQL)
-- I COULDN'T GET IT TO WORK PROPERLY

-- CREATE ROLE Read_Only_User WITH LOGIN PASSWORD 'Test1234';
-- \connect postgres;
-- GRANT CONNECT ON DATABASE postgres TO Read_Only_User;
-- GRANT USAGE ON SCHEMA public TO Read_Only_User;
-- GRANT SELECT ON ALL TABLES IN SCHEMA public TO Read_Only_User;
