spring:
    application:
      name: rest-api
    jpa:
      hibernate:
        ddl-auto: none
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
      username: disysuser
      password: disyspw
    flyway:
        enabled: true
        baseline-on-migrate: true
